/** @type {import('tailwindcss').Config} */
export default {
  content: ["./src/**/*.{html,js,css}", "./index.html", "./src/style.css"],
  darkMode: "selector",
  theme: {
    extend: {
      colors: {
        bg: "rgb(var(--c-bg) / <alpha-value>)",
        surface: "rgb(var(--c-surface) / <alpha-value>)",
        "surface-hover": "rgb(var(--c-surface-hover) / <alpha-value>)",
        border: "rgb(var(--c-border) / <alpha-value>)",
        "border-muted": "rgb(var(--c-border-muted) / <alpha-value>)",
        text: "rgb(var(--c-text) / <alpha-value>)",
        "text-muted": "rgb(var(--c-text-muted) / <alpha-value>)",
        "text-muted-hover": "rgb(var(--c-text-muted-hover) / <alpha-value>)",
        "text-subtle": "rgb(var(--c-text-subtle) / <alpha-value>)",
        focus: "rgb(var(--c-focus) / <alpha-value>)",
        "scrollbar-thumb-hover": "rgb(var(--c-scrollbar-thumb-hover) / <alpha-value>)",
        primary: "rgb(var(--c-primary) / <alpha-value>)",
        "primary-hover": "rgb(var(--c-primary-hover) / <alpha-value>)",
        "on-primary": "rgb(var(--c-on-primary) / <alpha-value>)",
        success: "rgb(var(--c-success) / <alpha-value>)",
        "success-subtle": "rgb(var(--c-success-subtle) / <alpha-value>)",
        "success-border": "rgb(var(--c-success-border) / <alpha-value>)",
        "success-text": "rgb(var(--c-success-text) / <alpha-value>)",
        warning: "rgb(var(--c-warning) / <alpha-value>)",
        "warning-subtle": "rgb(var(--c-warning-subtle) / <alpha-value>)",
        "warning-border": "rgb(var(--c-warning-border) / <alpha-value>)",
        "warning-text": "rgb(var(--c-warning-text) / <alpha-value>)",
        danger: "rgb(var(--c-danger) / <alpha-value>)",
        "danger-subtle": "rgb(var(--c-danger-subtle) / <alpha-value>)",
        "danger-border": "rgb(var(--c-danger-border) / <alpha-value>)",
        "danger-text": "rgb(var(--c-danger-text) / <alpha-value>)",
      },
    },
  },
  plugins: [],
};
